site_name: Multi Touch Web Development
theme:
  name: 'material'
  custom_dir: 'theme_customization'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.critic
  - codehilite
